import type { ReactNode } from 'react';
import { parentalLeaveRules } from './config/parentalLeaveRules.ts';

const REPOSITORY_URL = 'https://github.com/Zendelo/flexible-parental-leave-planner';
const ISSUE_URL = `${REPOSITORY_URL}/issues/new/choose`;
const TERMS_EFFECTIVE_DATE = '30 August 2026';
const PRIVACY_UPDATED_DATE = '30 August 2026';

function Layout({ title, children }: { title: string; children: ReactNode }) {
  return (
    <main className="legal-page">
      <a className="text-button" href="/">← Back to planner</a>
      <h1>{title}</h1>
      {children}
      <footer>
        <p>
          <strong>Flexible Parental Leave Planner</strong>
          <br />
          Independent guidance and planning tool — not legal advice.
        </p>
        <p>
          Not affiliated with or endorsed by the Fair Work Ombudsman, Fair Work
          Commission, Australian Government, or any state or territory government.
        </p>
        <p>Rules last checked: {parentalLeaveRules.rulesLastVerified}</p>
      </footer>
    </main>
  );
}

export function TermsPage() {
  return (
    <Layout title="Terms of Use">
      <p className="lead">
        These terms apply to use of the hosted Flexible Parental Leave Planner.
      </p>
      <p><strong>Effective:</strong> {TERMS_EFFECTIVE_DATE}</p>

      <h2>Purpose of the service</h2>
      <p>
        The planner provides general educational information, calculations and
        planning estimates only. It does not provide legal, employment,
        financial or workplace-relations advice. It does not represent you,
        communicate with an employer, submit statutory notices, determine a
        legal entitlement, or guarantee any employment outcome.
      </p>

      <h2>Accuracy and assumptions</h2>
      <p>
        Results use information supplied by you, implemented statutory rules
        and selected assumptions. Individual circumstances may produce a
        different outcome. Relevant matters can include notices already given,
        employer agreements, awards, enterprise agreements, workplace policies,
        public holidays and changes to legislation or official guidance.
      </p>
      <p>
        Reasonable efforts are made to maintain the planner, its source
        references and its tests, but no representation is made that every
        calculation, interpretation, source, holiday date or item of guidance
        will always be complete, current or error-free.
      </p>

      <h2>Your responsibility</h2>
      <p>
        You are responsible for checking the information you enter, reviewing
        the assumptions shown with a result, meeting any applicable notice
        requirements, and verifying important decisions against current
        official information or advice appropriate to your circumstances.
      </p>

      <h2>No professional relationship</h2>
      <p>
        Using the planner does not create a solicitor-client, adviser-client,
        employment, agency or other professional relationship.
      </p>

      <h2>Employer decisions and individual circumstances</h2>
      <p>
        Some scenarios may depend on employer agreement or circumstances that
        this planner cannot assess. The planner cannot determine whether a
        particular request or notice satisfies every legal requirement or
        whether an employer is required or likely to agree to a proposed
        arrangement.
      </p>

      <h2>Changes and availability</h2>
      <p>
        Legislation, government guidance, public-holiday data and this planner
        can change. Results generated at one time may not remain correct later.
        The service may also be changed, corrected, suspended or withdrawn.
      </p>

      <h2>External sources and links</h2>
      <p>
        Links to legislation and government websites are provided so users can
        verify current official information. Those sites are controlled by
        their respective operators and may change independently of this
        project.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, the operator excludes liability
        for loss or damage arising from reliance solely on an estimate,
        projection or scenario generated by this tool, including where a result
        is affected by inaccurate or incomplete information entered by the
        user, assumptions selected by the user, employer-specific
        circumstances, changes to legislation or official guidance, or matters
        outside the stated scope of the planner.
      </p>
      <p>
        To the maximum extent permitted by law, the operator does not warrant
        that the service will be uninterrupted, error-free, or suitable for a
        particular user's individual circumstances.
      </p>

      <h2>Rights that cannot be excluded</h2>
      <p>
        Nothing in these Terms excludes, restricts or modifies any consumer
        guarantee, right, remedy or liability that cannot lawfully be excluded,
        restricted or modified, including under the Australian Consumer Law.
      </p>

      <h2>Open-source software</h2>
      <p>
        The project's source code is separately made available under the MIT
        License. That licence governs copying, modification and redistribution
        of the source code. These Terms govern use of the hosted planning
        service.
      </p>

      <h2>Independent service</h2>
      <p>
        The Flexible Parental Leave Planner is independent. It is not operated
        by, affiliated with, endorsed by, or an official service of the Fair
        Work Ombudsman, Fair Work Commission, Australian Government, or any
        state or territory government.
      </p>

      <h2>Report an issue</h2>
      <p>
        <a href={ISSUE_URL} rel="noreferrer" target="_blank">
          Found a calculation or legal-data issue? Report it on GitHub
        </a>.
        {' '}Please describe the calculation generically and do not include
        names, child names, employer details or unnecessary personal
        information.
      </p>
    </Layout>
  );
}

export function PrivacyPage() {
  return (
    <Layout title="Privacy">
      <p className="lead">Calculator inputs are designed to stay on your device.</p>
      <p><strong>Last updated:</strong> {PRIVACY_UPDATED_DATE}</p>

      <h2>Calculator inputs</h2>
      <p>
        This static calculator processes the child's date of birth, leave
        dates, return date, work pattern and extension-request date in the
        browser. The current application source does not configure an
        application backend, analytics, session replay or error-reporting
        service that receives those calculator inputs.
      </p>

      <h2>Technical information used to serve the site</h2>
      <p>
        Like other websites, the hosting provider may automatically process
        technical request information needed to deliver the site, such as an
        IP address, browser or device information, requested pages, timestamps
        and security or server logs. This is separate from the calculator's
        in-browser calculation state.
      </p>

      <h2>Local browser behaviour</h2>
      <p>
        The planner does not require an account. Unless the application is
        changed in a future release, calculator inputs are not intentionally
        stored remotely by the application.
      </p>

      <h2>Future services</h2>
      <p>
        If analytics, security tooling, error reporting, contact forms,
        accounts or other services are added, this policy should be updated
        before those features are released. Calculator inputs should not be
        captured by analytics, form autocapture, session replay or error logs.
      </p>

      <h2>Open-source issue reports</h2>
      <p>
        GitHub issues are public. Do not post names, employer details, child
        names, private correspondence or other unnecessary identifying
        information when reporting a calculation problem.
      </p>

      <h2>Questions or corrections</h2>
      <p>
        For calculation, source or documentation corrections that do not
        contain private information, use the project's
        {' '}<a href={ISSUE_URL} rel="noreferrer" target="_blank">GitHub issue templates</a>.
        Do not use a public GitHub issue for a private security or privacy
        matter; follow the repository's Security Policy instead.
      </p>

      <p>
        This page describes the application's current design and does not by
        itself determine whether a particular operator is subject to the
        Privacy Act 1988 or the Australian Privacy Principles.
      </p>
    </Layout>
  );
}
